name: Add RSS to Freshrss

on:
  push:
    branches:
      - 'main'
    paths:
      - 'data/links.json'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth:  0

      - name: Install dependencies
        run: |
          sudo apt update -y && sudo apt install -y jq curl

      - name: Get new links
        run: |
          bash script/getNewLinks.sh > /tmp/newLinks.json
          cat /tmp/newLinks.json

      - name: To freshrss
        run: bash script/toFreshrss.sh /tmp/newLinks.json
        env: 
          G_API_TOKEN: ${{ secrets.G_API_TOKEN }}